package com.prashant.apilib.common;

public enum ErrorCodeEnum {
    UNKNOWN_ERROR,
    NO_NETWORK,
    JSON_FORMAT_ERROR,
    INTERNAL_SERVER_ERROR,
    BAD_INPUT,
    RESOURCE_NOT_FOUND,
    INVALID_CREDENTIALS,
    INPUT_ERROR,
    ALREADY_UP_TO_DATE,
    NO_DATA_FOUND,
    MANDATORY_DATA_MISSING,
    ERROR_IN_QUERY,
    SOMETHING_WENT_WRONG,
    EMAIL_ALREADY_ASSIGNED,
    PHONE_ALREADY_ASSIGNED,
    TIME_ZONE_ERROR,
    LOCATION_VALIDATION_ERROR,
    ALREADY_CHECKED_OUT,
    LEAVE_REQUEST_EXIST,
    ALREADY_LOGGED_IN,
    INVALID_ATTEMPT,
    INVALID_TOKEN
}
